# Generated by Django 4.2.6 on 2023-11-23 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('access', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('name', 'access')},
            },
        ),
        migrations.CreateModel(
            name='WaterSystemConditions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=30)),
                ('conditions', models.TextField()),
                ('temp', models.FloatField()),
                ('cfs', models.IntegerField()),
                ('air_temp', models.IntegerField()),
                ('water_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watersystem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('description', models.TextField()),
                ('dry_fly', models.BooleanField(default=False)),
                ('nymph_fly', models.BooleanField(default=False)),
                ('streamer_fly', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('name', 'size')},
            },
        ),
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fish_type', models.CharField(max_length=255)),
                ('fish_size', models.FloatField()),
                ('date_caught', models.DateField()),
                ('time_of_day', models.DateTimeField()),
                ('landed_fly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_catches', to='api.fly')),
                ('other_fly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fly_not_hooked_catches', to='api.fly')),
                ('water_system_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watersystemconditions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
