version: '3.8'

services:
  mysql:
    image: mysql:8.2.0
    environment:
      MYSQL_DATABASE: FISH_APP
      MYSQL_USER: user
      MYSQL_PASSWORD: Steven32!!
      MYSQL_ROOT_PASSWORD: Steven32!!
    ports:
      - "3307:3306"
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: FISH_APP
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Steven32!!  # Set the password for the user
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
      

networks:
  backend:

volumes:
  mysql_data:
  postgres_data:



